// Code generated by go generate; DO NOT EDIT.
package cexp

type StringGetter func() string

func String(condition bool, v1, v2 string) string {
	if condition {
		return v1
	}
	return v2
}

func StringShortCircuit(condition bool, g1, g2 StringGetter) string {
	if condition {
		return g1()
	}
	return g2()
}

type IntGetter func() int

func Int(condition bool, v1, v2 int) int {
	if condition {
		return v1
	}
	return v2
}

func IntShortCircuit(condition bool, g1, g2 IntGetter) int {
	if condition {
		return g1()
	}
	return g2()
}

type UintGetter func() uint

func Uint(condition bool, v1, v2 uint) uint {
	if condition {
		return v1
	}
	return v2
}

func UintShortCircuit(condition bool, g1, g2 UintGetter) uint {
	if condition {
		return g1()
	}
	return g2()
}
