// The following directive is necessary to make the package coherent:

// +build ignore

// This program generates:
// - type_assert.go
// It can be invoked by running go generate
package main

import (
	"log"
	"strings"

	"github.com/QisFj/godry/gen"
)

func main() {
	types := gen.ParseFlagTypes()
	log.Printf("types: \n- '%s'\n", strings.Join(types, "'\n- '"))
	gen.Gen("type_assert", T, types)
}

const T = `// Code generated by go generate; DO NOT EDIT.
package assert

import "fmt"
<< range $t := .>>
func <<$t | Title>>(v interface{}) <<$t>> {
	i, ok := v.(<<$t>>)
	Assert(ok, "type assert: <<$t>>", map[string]interface{}{
		"type":  fmt.Sprintf("%T", v),
		"value": fmt.Sprintf("%v", v),
	}, CallerOption(1, false))
	return i
}
<< end >>`
